// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLDxwyONHQucztgJRRhaSqd72HnUBfxF8',
    appId: '1:976609462041:web:f126f837644b5dd7eca788',
    messagingSenderId: '976609462041',
    projectId: 'connect-7cfe3',
    authDomain: 'connect-7cfe3.firebaseapp.com',
    storageBucket: 'connect-7cfe3.appspot.com',
    measurementId: 'G-RKEBCSFVTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxDnqBe_lnct_aaoDMujTrdBSaozF_A3o',
    appId: '1:976609462041:android:e9b6fd54cb907c5feca788',
    messagingSenderId: '976609462041',
    projectId: 'connect-7cfe3',
    storageBucket: 'connect-7cfe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvJ0QQvY-BcIUW-KNhgIQ9Wc_FDF4HrqY',
    appId: '1:976609462041:ios:6a6692a44929b554eca788',
    messagingSenderId: '976609462041',
    projectId: 'connect-7cfe3',
    storageBucket: 'connect-7cfe3.appspot.com',
    iosBundleId: 'com.example.failedFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvJ0QQvY-BcIUW-KNhgIQ9Wc_FDF4HrqY',
    appId: '1:976609462041:ios:af874f37573aed68eca788',
    messagingSenderId: '976609462041',
    projectId: 'connect-7cfe3',
    storageBucket: 'connect-7cfe3.appspot.com',
    iosBundleId: 'com.example.failedFirebase.RunnerTests',
  );
}
